### ISSUE TITLE
Export Tiles from QuPath with multiple classes

### ISSUE THREAD

**Issue by aaronsathya** [andreped/NoCodeSeg#4]
First some context: I am attempting to obtain multi-class segmentation of cerebellum tissue with different cellular layers corresponding to separate classes. I have annotated four classes: 'EGL', 'Molecular layer', 'IGL', and 'WM' on QuPath. I tested export tiles with multiple classes from QuPath using two the two different scripts available. Here are the issues I am having with both:

1. The [script](https://github.com/andreped/NoCodeSeg/blob/25bb5f732e1705b7309415ff382df6f9c5ee79f6/source/exportTiles_multiclass.groovy) by @andreped is giving me an error:

ERROR: MissingMethodException at line 61: No signature of method: qupath.lib.images.writers.TileExporter.labeledServer() is applicable for argument types: (qupath.lib.images.servers.LabeledImageServer$Builder) values: [qupath.lib.images.servers.LabeledImageServer$Builder@7bf3c609]
Possible solutions: labeledServer(qupath.lib.images.servers.ImageServer)

ERROR: org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:70)
    org.codehaus.groovy.runtime.callsite.PojoMetaClassSite.call(PojoMetaClassSite.java:46)
    org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
    org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
    org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139)
    Script16.run(Script16.groovy:62)
    org.codehaus.groovy.jsr223.GroovyScriptEngineImpl.eval(GroovyScriptEngineImpl.java:317)
    org.codehaus.groovy.jsr223.GroovyScriptEngineImpl.eval(GroovyScriptEngineImpl.java:155)
    qupath.lib.gui.scripting.DefaultScriptEditor.executeScript(DefaultScriptEditor.java:982)
    qupath.lib.gui.scripting.DefaultScriptEditor.executeScript(DefaultScriptEditor.java:914)
    qupath.lib.gui.scripting.DefaultScriptEditor.executeScript(DefaultScriptEditor.java:829)
    qupath.lib.gui.scripting.DefaultScriptEditor$2.run(DefaultScriptEditor.java:1345)
    java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
    java.base/java.util.concurrent.FutureTask.run(Unknown Source)
    java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    java.base/java.lang.Thread.run(Unknown Source)

2. The [script](source/qupath_export_tiles_annotation_multiclass.groovy) by @pr4deepr is yielding what I need (see below), however, many of the tiles are just background. Is there a way to incorporate the glassthreshold in the script by @andreped to avoid the tiles with too much background? Additionally, in order to get this script to work, I had to edit [this line](https://github.com/andreped/NoCodeSeg/blob/f2785d53768467ec1c9130880bdf7a0dd5f0488b/source/qupath_export_tiles_annotation_multiclass.groovy#L26) to `.multichannelOutput(false)`.

![20211026_Javid_01Image_01 vsi - 20x  d=5 79044,x=10376,y=36318,w=2965,h=2964](https://user-images.githubusercontent.com/17412131/149586843-ab3d500b-9602-46c1-b3cf-5dac80495c63.png)

**Comment by andreped** [comment]
> 1. The [script](https://github.com/andreped/NoCodeSeg/blob/25bb5f732e1705b7309415ff382df6f9c5ee79f6/source/exportTiles_multiclass.groovy) by @andreped is giving me an error:

Yeah, that is my bad. I was hoping for @SahPet to test the script before people got the chance to test it, but since the bug was so obvious, I fixed it right away. Run some initial tests in batch mode. Seems to run. See [recent commit](https://github.com/andreped/NoCodeSeg/commit/f2785d53768467ec1c9130880bdf7a0dd5f0488b) for changes.

Hence, this more generic script should work now:
https://github.com/andreped/NoCodeSeg/blob/main/source/exportTiles_multiclass.groovy

This script has simply incorporated some of @pr4deepr's ideas to support multi-class export.
Let me know if it still does not work, and I can try to fix it straight away.

To neglect patches containing little tissue, you can try increasing `percentageThreshold` (range [0.0, 1.0], for instance to 0.7).

**Comment by aaronsathya** [comment]
Great! It works in that I am able to get the necessary. But all classes seem to have collapsed into the first class color
![20211026_Javid_01Image_01 vsi - 20x  d=4,x=10752,y=36864,w=2048,h=2048](https://user-images.githubusercontent.com/17412131/149590702-3fbf114c-5ff9-4141-9591-de564a59d139.png)
?

**Comment by andreped** [comment]
@aaronsathya yeah, wish I had time to debug it myself before commit...

I found the bug, see here for details: https://github.com/andreped/NoCodeSeg/commit/4b6754cd2ecc50d06aacc000cde90072315afca8

Try again with newest version:
https://github.com/andreped/NoCodeSeg/blob/main/source/importPyramidalTIFF_multiclass.groovy

**Comment by aaronsathya** [comment]
Worked!

![20211026_Javid_01Image_01 vsi - 20x  d=4,x=10752,y=36864,w=2048,h=2048](https://user-images.githubusercontent.com/17412131/149592484-63c4fe81-cdb3-4093-809c-de7d0075a4f4.png)

**Comment by andreped** [comment]
Great! Did you mange to filter glass dominant patches as well?

Also remember that it is important to have some negative patches for training. They are useful for making more robust models, but it is true that having too many of them might degrade performance.

Let me know if you get any issues with MIB :] Should work out of the box. Just follow the tutorial video, and you should be all set:
https://youtu.be/9dTfUwnL6zY?t=188

Ilya Belevich @Ajaxels, the lead developer of MIB, also has a YouTube channel, which contains a lot of useful tricks on how to use MIB and what it can be used for - also info on how to train deep segmentation models:
https://www.youtube.com/watch?v=gk1GK_hWuGE&ab_channel=IlyaBelevich

Might be useful if you are wondering which hyperparameters to use for optimization relevant for training, for instance.
