### ISSUE TITLE
Network and config files

### ISSUE THREAD

**Issue by ajr82** [andreped/NoCodeSeg#7]
Hi Andre, 
Would it be possible to share the .mibDeep and .migCfg files for the H&E epithelium model?
Thank you!

**Comment by andreped** [comment]
@ajr82 I have contacted the first author (@SahPet) and he will send me the files soon. I will let you know when they are ready to download :]

**Comment by andreped** [comment]
@ajr82 seems like people are on winter holiday in Norway this week. Hence, I cannot access and upload the model files until next week.

**Comment by SahPet** [comment]
Hi ajr82!

Sorry about the late reply. Here are the best performing U-nets for the HE-dataset with input 256x256 and 512x512. They are additionally trained with hardmining so slightly better performance than the once in the paper. Ilya Belevic and I have experimented with training Google DeepLabV3plus with Resnet18 as a backbone lately with DeepMIB, which further increases performance (Ilya will probably realease this addtion to DeepMIB shortly). Here are the U-nets (*.mibDeep files) shared on my Google Drive: https://drive.google.com/drive/folders/1CgLdIpiM7Rn2v30V0NLor0tTtZmllD7Y?usp=sharing
There is a bit sparse augmentation during training, so they can probably be further improved with optimization of augmentation settings. I may post a similarly trained deeplabV3plusResnet18 *.mibdeep files here as well shortly.

**Comment by andreped** [comment]
@SahPet important that we post the models used for the paper here, at least firstly.

**Comment by ajr82** [comment]
Hi @andreped and @SahPet, thank you very much!

**Comment by SahPet** [comment]
Hi again @ajr82! So I added a IBDColEpi HE trained deeplabV3resnet18 *.mibDeep-file now too. It achieves a mean IoU score of 0.9710 on the IBDColEpi dataset. Added to the same folder: https://drive.google.com/drive/folders/1CgLdIpiM7Rn2v30V0NLor0tTtZmllD7Y?usp=sharing
Compared to the U-nets the GPU-requirement for training is much smaller, the size of the mibdeep-file is much smaller, running inference is faster - it's generally quite a bit better than the U-nets. They have a tendency to overfit, but nothing you can't adjust for using heavy augmentation during training. I'm not quite ready to share the mibcfg file yet for this one, need to figure out if it's going to be part of a publication first.

**Comment by SahPet** [comment]
> @SahPet important that we post the models used for the paper here, at least firstly.

I'll do that later. We can share additional network files if we want too though.

**Comment by andreped** [comment]
@ajr82 the best performing models (512, separate models for HE and CD3) have been uploaded to the Google Drive:
https://drive.google.com/drive/folders/1eUVs1DA1UYayUYjr8_aY3O5xDgV1uLvH

Download the zip file "trained-models.zip".

I have also sent a request to [DataverseNO](https://dataverse.no/dataset.xhtml?persistentId=doi:10.18710/TLA01U) to get the models added there as well.

However, we cannot upload the models to the github itself, as github is not meant to store these types of data. They simple are too large. I will update the README when this is done.

Note that **you only need the .mibDeep files to use the two models in MIB**. The .mibCfg files are not needed.

**Comment by ajr82** [comment]
@andreped and @SahPet Thank you very much!

**Comment by ajr82** [comment]
> > @SahPet important that we post the models used for the paper here, at least firstly.
> 
> It's there now (https://drive.google.com/drive/folders/1CgLdIpiM7Rn2v30V0NLor0tTtZmllD7Y?usp=sharing). We can of course share additional network files if we want too though.



> Hi again @ajr82! I was going to add a IBDColEpi HE trained deeplabV3resnet18 *.mibDeep-file, but need to figure out if it's going to be part of a publication first.

It would be nice to see the outcome of this model too. We eventually plan on publishing giving due credit to you both.  If the deeplabv3resnet18 model cannot be used to analyze data that will be published, we will not use it for the publication.

**Comment by andreped** [comment]
The U-Net model should work quite well. There will always be a better model in the future. We will let you know when it is available.
